export const styleSuggestionMap = {
  "accent-color": ["auto"],
  "align-content": [
    "normal",
    "baseline-position",
    "content-distribution",
    "overflow-position",
    "content-position",
  ],
  "align-items": [
    "normal",
    "stretch",
    "baseline-position",
    "overflow-position",
    "self-position",
  ],
  "align-self": [
    "auto",
    "normal",
    "stretch",
    "baseline-position",
    "overflow-position",
    "self-position",
  ],
  "align-tracks": [
    "normal",
    "baseline-position",
    "content-distribution",
    "overflow-position",
    "content-position",
  ],
  all: [
    "initial",
    "inherit",
    "unset",
    "revert",
    "revert-layer",
  ],
  "anchor-name": ["none", "dashed-ident"],
  "anchor-scope": ["none", "all", "dashed-ident"],
  animation: ["single-animation"],
  "animation-composition": [],
  "animation-delay": [],
  "animation-direction": [],
  "animation-duration": [],
  "animation-fill-mode": [],
  "animation-iteration-count": [
    "single-animation-iteration-count",
  ],
  "animation-name": ["none"],
  "animation-play-state": [],
  "animation-range": [],
  "animation-range-end": ["normal"],
  "animation-range-start": ["normal"],
  "animation-timeline": ["single-animation-timeline"],
  "animation-timing-function": ["easing-function"],
  appearance: [
    "none",
    "auto",
    "textfield",
    "menulist-button",
    "compat-auto",
  ],
  "aspect-ratio": ["auto", "ratio"],
  azimuth: [
    "left-side",
    "far-left",
    "left",
    "center-left",
    "center",
    "center-right",
    "right",
    "far-right",
    "right-side",
    "behind",
    "leftwards",
    "rightwards",
  ],
  "backdrop-filter": ["none"],
  "backface-visibility": ["visible", "hidden"],
  background: ["bg-layer", "final-bg-layer"],
  "background-attachment": ["attachment"],
  "background-blend-mode": ["blend-mode"],
  "background-clip": ["box"],
  "background-color": [],
  "background-image": ["bg-image"],
  "background-origin": ["box"],
  "background-position": ["bg-position"],
  "background-position-x": [
    "center",
    "left",
    "right",
    "x-start",
    "x-end",
  ],
  "background-position-y": [
    "center",
    "top",
    "bottom",
    "y-start",
    "y-end",
  ],
  "background-repeat": ["repeat-style"],
  "background-size": ["bg-size"],
  "block-size": [],
  border: ["line-width", "line-style"],
  "border-block": [],
  "border-block-color": [],
  "border-block-end": [],
  "border-block-end-color": [],
  "border-block-end-style": [],
  "border-block-end-width": [],
  "border-block-start": [],
  "border-block-start-color": [],
  "border-block-start-style": [],
  "border-block-start-width": [],
  "border-block-style": [],
  "border-block-width": [],
  "border-bottom": ["line-width", "line-style"],
  "border-bottom-color": [],
  "border-bottom-left-radius": [],
  "border-bottom-right-radius": [],
  "border-bottom-style": ["line-style"],
  "border-bottom-width": ["line-width"],
  "border-collapse": ["collapse", "separate"],
  "border-color": [],
  "border-end-end-radius": [],
  "border-end-start-radius": [],
  "border-image": [],
  "border-image-outset": [],
  "border-image-repeat": [
    "stretch",
    "repeat",
    "round",
    "space",
  ],
  "border-image-slice": ["number-percentage", "fill"],
  "border-image-source": ["none"],
  "border-image-width": ["auto"],
  "border-inline": [],
  "border-inline-color": [],
  "border-inline-end": [],
  "border-inline-end-color": [],
  "border-inline-end-style": [],
  "border-inline-end-width": [],
  "border-inline-start": [],
  "border-inline-start-color": [],
  "border-inline-start-style": [],
  "border-inline-start-width": [],
  "border-inline-style": [],
  "border-inline-width": [],
  "border-left": ["line-width", "line-style"],
  "border-left-color": [],
  "border-left-style": ["line-style"],
  "border-left-width": ["line-width"],
  "border-radius": [],
  "border-right": ["line-width", "line-style"],
  "border-right-color": [],
  "border-right-style": ["line-style"],
  "border-right-width": ["line-width"],
  "border-spacing": [],
  "border-start-end-radius": [],
  "border-start-start-radius": [],
  "border-style": ["line-style"],
  "border-top": ["line-width", "line-style"],
  "border-top-color": [],
  "border-top-left-radius": [],
  "border-top-right-radius": [],
  "border-top-style": ["line-style"],
  "border-top-width": ["line-width"],
  "border-width": ["line-width"],
  bottom: ["auto"],
  "box-align": [
    "start",
    "center",
    "end",
    "baseline",
    "stretch",
  ],
  "box-decoration-break": ["slice", "clone"],
  "box-direction": ["normal", "reverse", "inherit"],
  "box-flex": [],
  "box-flex-group": ["integer"],
  "box-lines": ["single", "multiple"],
  "box-ordinal-group": ["integer"],
  "box-orient": [
    "horizontal",
    "vertical",
    "inline-axis",
    "block-axis",
    "inherit",
  ],
  "box-pack": ["start", "center", "end", "justify"],
  "box-shadow": ["none", "shadow"],
  "box-sizing": ["content-box", "border-box"],
  "break-after": [
    "auto",
    "avoid",
    "always",
    "all",
    "avoid-page",
    "page",
    "left",
    "right",
    "recto",
    "verso",
    "avoid-column",
    "column",
    "avoid-region",
    "region",
  ],
  "break-before": [
    "auto",
    "avoid",
    "always",
    "all",
    "avoid-page",
    "page",
    "left",
    "right",
    "recto",
    "verso",
    "avoid-column",
    "column",
    "avoid-region",
    "region",
  ],
  "break-inside": [
    "auto",
    "avoid",
    "avoid-page",
    "avoid-column",
    "avoid-region",
  ],
  "caption-side": ["top", "bottom"],
  caret: [],
  "caret-color": ["auto"],
  "caret-shape": ["auto", "bar", "block", "underscore"],
  clear: [
    "none",
    "left",
    "right",
    "both",
    "inline-start",
    "inline-end",
  ],
  clip: ["shape", "auto"],
  "clip-path": ["none"],
  "clip-rule": ["nonzero", "evenodd"],
  color: [],
  "color-interpolation-filters": ["auto", "linear"],
  "color-scheme": [
    "normal",
    "light",
    "dark",
    "custom-ident",
    "only",
  ],
  "column-count": ["integer", "auto"],
  "column-fill": ["auto", "balance"],
  "column-gap": ["normal"],
  "column-rule": [],
  "column-rule-color": [],
  "column-rule-style": [],
  "column-rule-width": [],
  "column-span": ["none", "all"],
  "column-width": ["auto"],
  columns: [],
  contain: [
    "none",
    "strict",
    "content",
    "size",
    "inline-size",
    "layout",
    "style",
    "paint",
  ],
  "contain-intrinsic-block-size": ["auto", "none"],
  "contain-intrinsic-height": ["auto", "none"],
  "contain-intrinsic-inline-size": ["auto", "none"],
  "contain-intrinsic-size": ["auto", "none"],
  "contain-intrinsic-width": ["auto", "none"],
  container: [],
  "container-name": ["none", "custom-ident"],
  "container-type": ["normal", "size", "inline-size"],
  content: [
    "normal",
    "none",
    "content-replacement",
    "content-list",
    "string",
    "counter",
  ],
  "content-visibility": ["visible", "auto", "hidden"],
  "counter-increment": ["counter-name", "integer", "none"],
  "counter-reset": [
    "counter-name",
    "integer",
    "reversed-counter-name",
    "integer",
    "none",
  ],
  "counter-set": ["counter-name", "integer", "none"],
  cursor: [
    "url",
    "x",
    "y",
    "auto",
    "default",
    "none",
    "context-menu",
    "help",
    "pointer",
    "progress",
    "wait",
    "cell",
    "crosshair",
    "text",
    "vertical-text",
    "alias",
    "copy",
    "move",
    "no-drop",
    "not-allowed",
    "e-resize",
    "n-resize",
    "ne-resize",
    "nw-resize",
    "s-resize",
    "se-resize",
    "sw-resize",
    "w-resize",
    "ew-resize",
    "ns-resize",
    "nesw-resize",
    "nwse-resize",
    "col-resize",
    "row-resize",
    "all-scroll",
    "zoom-in",
    "zoom-out",
    "grab",
    "grabbing",
  ],
  cx: [],
  cy: [],
  d: ["none", "path", "string"],
  direction: ["ltr", "rtl"],
  display: [
    "none",
    "block",
    "inline",
    "inline-block",
    "flex",
    "grid",
    "none",
  ],
  "dominant-baseline": [
    "auto",
    "text-bottom",
    "alphabetic",
    "ideographic",
    "middle",
    "central",
    "mathematical",
    "hanging",
    "text-top",
  ],
  "empty-cells": ["show", "hide"],
  "field-sizing": ["content", "fixed"],
  fill: ["paint"],
  "fill-opacity": [],
  "fill-rule": ["nonzero", "evenodd"],
  filter: ["none", "filter-function-list"],
  flex: ["none"],
  "flex-basis": ["content"],
  "flex-direction": [
    "row",
    "row-reverse",
    "column",
    "column-reverse",
  ],
  "flex-flow": [],
  "flex-grow": [],
  "flex-shrink": [],
  "flex-wrap": ["nowrap", "wrap", "wrap-reverse"],
  float: [
    "left",
    "right",
    "none",
    "inline-start",
    "inline-end",
  ],
  "flood-color": [],
  "flood-opacity": [],
  font: [
    "font-variant-css",
    "caption",
    "icon",
    "menu",
    "message-box",
    "small-caption",
    "status-bar",
  ],
  "font-family": ["family-name", "generic-family"],
  "font-feature-settings": ["normal", "feature-tag-value"],
  "font-kerning": ["auto", "normal", "none"],
  "font-language-override": ["normal", "string"],
  "font-optical-sizing": ["auto", "none"],
  "font-palette": [
    "normal",
    "light",
    "dark",
    "palette-identifier",
    "palette-mix",
  ],
  "font-size": [],
  "font-size-adjust": [
    "none",
    "ex-height",
    "cap-height",
    "ch-width",
    "ic-width",
    "ic-height",
    "from-font",
  ],
  "font-smooth": ["auto", "never", "always"],
  "font-stretch": ["font-stretch-absolute"],
  "font-style": ["normal", "italic", "oblique"],
  "font-synthesis": [
    "none",
    "weight",
    "style",
    "small-caps",
    "position",
  ],
  "font-synthesis-position": ["auto", "none"],
  "font-synthesis-small-caps": ["auto", "none"],
  "font-synthesis-style": ["auto", "none"],
  "font-synthesis-weight": ["auto", "none"],
  "font-variant": [
    "normal",
    "none",
    "stylistic",
    "historical-forms",
    "styleset",
    "character-variant",
    "swash",
    "ornaments",
    "annotation",
    "small-caps",
    "all-small-caps",
    "petite-caps",
    "all-petite-caps",
    "unicase",
    "titling-caps",
    "numeric-figure-values",
    "numeric-spacing-values",
    "numeric-fraction-values",
    "ordinal",
    "slashed-zero",
    "east-asian-variant-values",
    "east-asian-width-values",
    "ruby",
  ],
  "font-variant-alternates": [
    "normal",
    "stylistic",
    "historical-forms",
    "styleset",
    "character-variant",
    "swash",
    "ornaments",
    "annotation",
  ],
  "font-variant-caps": [
    "normal",
    "small-caps",
    "all-small-caps",
    "petite-caps",
    "all-petite-caps",
    "unicase",
    "titling-caps",
  ],
  "font-variant-east-asian": [
    "normal",
    "east-asian-variant-values",
    "east-asian-width-values",
    "ruby",
  ],
  "font-variant-emoji": [
    "normal",
    "text",
    "emoji",
    "unicode",
  ],
  "font-variant-ligatures": ["normal", "none"],
  "font-variant-numeric": [
    "normal",
    "ordinal",
    "slashed-zero",
  ],
  "font-variant-position": ["normal", "sub", "super"],
  "font-variation-settings": ["normal", "string"],
  "font-weight": [
    "font-weight-absolute",
    "bolder",
    "lighter",
  ],
  "forced-color-adjust": [
    "auto",
    "none",
    "preserve-parent-color",
  ],
  gap: [],
  grid: ["auto-flow", "dense", "auto-flow", "dense"],
  "grid-area": ["grid-line", "grid-line"],
  "grid-auto-columns": ["track-size"],
  "grid-auto-flow": ["row", "column", "dense"],
  "grid-auto-rows": ["track-size"],
  "grid-column": ["grid-line", "grid-line"],
  "grid-column-end": ["grid-line"],
  "grid-column-gap": [],
  "grid-column-start": ["grid-line"],
  "grid-gap": [],
  "grid-row": ["grid-line", "grid-line"],
  "grid-row-end": ["grid-line"],
  "grid-row-gap": [],
  "grid-row-start": ["grid-line"],
  "grid-template": [
    "none",
    "line-names",
    "string",
    "track-size",
    "line-names",
    "explicit-track-list",
  ],
  "grid-template-areas": ["none", "string"],
  "grid-template-columns": [
    "none",
    "track-list",
    "auto-track-list",
    "subgrid",
    "line-name-list",
  ],
  "grid-template-rows": [
    "none",
    "track-list",
    "auto-track-list",
    "subgrid",
    "line-name-list",
  ],
  "hanging-punctuation": [
    "none",
    "first",
    "force-end",
    "allow-end",
    "last",
  ],
  height: [
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fit-content",
    "calc-size",
    "anchor-size",
  ],
  "hyphenate-character": ["auto", "string"],
  "hyphenate-limit-chars": ["auto", "integer"],
  hyphens: ["none", "manual", "auto"],
  "image-orientation": ["from-image", "flip"],
  "image-rendering": ["auto", "crisp-edges", "pixelated"],
  "image-resolution": ["from-image", "resolution", "snap"],
  "ime-mode": [
    "auto",
    "normal",
    "active",
    "inactive",
    "disabled",
  ],
  "initial-letter": ["normal", "integer"],
  "initial-letter-align": [
    "auto",
    "alphabetic",
    "hanging",
    "ideographic",
  ],
  "inline-size": [],
  "input-security": ["auto", "none"],
  inset: [],
  "inset-block": [],
  "inset-block-end": [],
  "inset-block-start": [],
  "inset-inline": [],
  "inset-inline-end": [],
  "inset-inline-start": [],
  "interpolate-size": [],
  isolation: ["auto"],
  "justify-content": ["normal", "left", "right"],
  "justify-items": [
    "normal",
    "stretch",
    "baseline-position",
    "overflow-position",
    "self-position",
    "left",
    "right",
    "legacy",
    "legacy",
    "left",
    "right",
    "center",
  ],
  "justify-self": [
    "auto",
    "normal",
    "stretch",
    "baseline-position",
    "overflow-position",
    "self-position",
    "left",
    "right",
  ],
  "justify-tracks": [
    "normal",
    "content-distribution",
    "overflow-position",
    "content-position",
    "left",
    "right",
  ],
  left: ["auto"],
  "letter-spacing": ["normal"],
  "lighting-color": [],
  "line-break": [
    "auto",
    "loose",
    "normal",
    "strict",
    "anywhere",
  ],
  "line-clamp": ["none", "integer"],
  "line-height": ["normal"],
  "line-height-step": [],
  "list-style": [],
  "list-style-image": ["none"],
  "list-style-position": ["inside", "outside"],
  "list-style-type": ["counter-style", "string", "none"],
  margin: [],
  "margin-block": [],
  "margin-block-end": [],
  "margin-block-start": [],
  "margin-bottom": ["auto"],
  "margin-inline": [],
  "margin-inline-end": [],
  "margin-inline-start": [],
  "margin-left": ["auto"],
  "margin-right": ["auto"],
  "margin-top": ["auto"],
  "margin-trim": ["none", "in-flow", "all"],
  marker: ["none", "url"],
  "marker-end": ["none", "url"],
  "marker-mid": ["none", "url"],
  "marker-start": ["none", "url"],
  mask: ["mask-layer"],
  "mask-border": [],
  "mask-border-mode": ["luminance", "alpha"],
  "mask-border-outset": [],
  "mask-border-repeat": [
    "stretch",
    "repeat",
    "round",
    "space",
  ],
  "mask-border-slice": ["number-percentage", "fill"],
  "mask-border-source": ["none"],
  "mask-border-width": ["auto"],
  "mask-clip": ["geometry-box", "no-clip"],
  "mask-composite": ["compositing-operator"],
  "mask-image": ["mask-reference"],
  "mask-mode": ["masking-mode"],
  "mask-origin": ["geometry-box"],
  "mask-position": ["position"],
  "mask-repeat": ["repeat-style"],
  "mask-size": ["bg-size"],
  "mask-type": ["luminance", "alpha"],
  "masonry-auto-flow": [
    "pack",
    "next",
    "definite-first",
    "ordered",
  ],
  "math-depth": ["auto-add", "add", "integer", "integer"],
  "math-shift": ["normal", "compact"],
  "math-style": ["normal", "compact"],
  "max-block-size": [],
  "max-height": [
    "none",
    "min-content",
    "max-content",
    "fit-content",
    "fit-content",
    "calc-size",
    "anchor-size",
  ],
  "max-inline-size": [],
  "max-lines": ["none", "integer"],
  "max-width": [
    "none",
    "min-content",
    "max-content",
    "fit-content",
    "fit-content",
    "calc-size",
    "anchor-size",
  ],
  "min-block-size": [],
  "min-height": [
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fit-content",
    "calc-size",
    "anchor-size",
  ],
  "min-inline-size": [],
  "min-width": [
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fit-content",
    "calc-size",
    "anchor-size",
  ],
  "mix-blend-mode": ["blend-mode", "plus-lighter"],
  "object-fit": [
    "fill",
    "contain",
    "cover",
    "none",
    "scale-down",
  ],
  "object-position": ["position"],
  offset: [],
  "offset-anchor": ["auto", "position"],
  "offset-distance": [],
  "offset-path": ["none", "offset-path", "coord-box"],
  "offset-position": ["normal", "auto", "position"],
  "offset-rotate": ["auto", "reverse"],
  opacity: ["opacity-value"],
  order: ["integer"],
  orphans: ["integer"],
  outline: [],
  "outline-color": ["auto"],
  "outline-offset": [],
  "outline-style": ["auto", "outline-line-style"],
  "outline-width": ["line-width"],
  overflow: ["visible", "hidden", "clip", "scroll", "auto"],
  "overflow-anchor": ["auto", "none"],
  "overflow-block": [
    "visible",
    "hidden",
    "clip",
    "scroll",
    "auto",
  ],
  "overflow-clip-box": ["padding-box", "content-box"],
  "overflow-clip-margin": ["visual-box"],
  "overflow-inline": [
    "visible",
    "hidden",
    "clip",
    "scroll",
    "auto",
  ],
  "overflow-wrap": ["normal", "break-word", "anywhere"],
  "overflow-x": [
    "visible",
    "hidden",
    "clip",
    "scroll",
    "auto",
  ],
  "overflow-y": [
    "visible",
    "hidden",
    "clip",
    "scroll",
    "auto",
  ],
  overlay: ["none", "auto"],
  "overscroll-behavior": ["contain", "none", "auto"],
  "overscroll-behavior-block": ["contain", "none", "auto"],
  "overscroll-behavior-inline": ["contain", "none", "auto"],
  "overscroll-behavior-x": ["contain", "none", "auto"],
  "overscroll-behavior-y": ["contain", "none", "auto"],
  padding: [],
  "padding-block": [],
  "padding-block-end": [],
  "padding-block-start": [],
  "padding-bottom": [],
  "padding-inline": [],
  "padding-inline-end": [],
  "padding-inline-start": [],
  "padding-left": [],
  "padding-right": [],
  "padding-top": [],
  page: ["auto", "custom-ident"],
  "page-break-after": [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "recto",
    "verso",
  ],
  "page-break-before": [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "recto",
    "verso",
  ],
  "page-break-inside": ["auto", "avoid"],
  "paint-order": ["normal", "fill", "stroke", "markers"],
  perspective: ["none"],
  "perspective-origin": ["position"],
  "place-content": [],
  "place-items": [],
  "place-self": [],
  "pointer-events": [
    "auto",
    "none",
    "visible",
    "ainted",
    "visible",
    "ill",
    "visible",
    "troke",
    "visible",
    "painted",
    "fill",
    "stroke",
    "all",
    "inherit",
  ],
  position: [
    "static",
    "relative",
    "absolute",
    "sticky",
    "fixed",
  ],
  "position-anchor": ["auto", "anchor-name"],
  "position-area": ["none", "position-area"],
  "position-try": [],
  "position-try-fallbacks": [
    "none",
    "dashed-ident",
    "try-tactic",
  ],
  "position-try-order": ["normal", "try-size"],
  "position-visibility": [
    "always",
    "anchors-valid",
    "anchors-visible",
    "no-overflow",
  ],
  "print-color-adjust": ["economy", "exact"],
  quotes: ["none", "auto", "string", "string"],
  r: [],
  resize: [
    "none",
    "both",
    "horizontal",
    "vertical",
    "block",
    "inline",
  ],
  right: ["auto"],
  rotate: ["none"],
  "row-gap": ["normal"],
  "ruby-align": [
    "start",
    "center",
    "space-between",
    "space-around",
  ],
  "ruby-merge": ["separate", "collapse", "auto"],
  "ruby-position": [
    "alternate",
    "over",
    "under",
    "inter-character",
  ],
  rx: [],
  ry: [],
  scale: ["none"],
  "scroll-behavior": ["auto", "smooth"],
  "scroll-margin": [],
  "scroll-margin-block": [],
  "scroll-margin-block-end": [],
  "scroll-margin-block-start": [],
  "scroll-margin-bottom": [],
  "scroll-margin-inline": [],
  "scroll-margin-inline-end": [],
  "scroll-margin-inline-start": [],
  "scroll-margin-left": [],
  "scroll-margin-right": [],
  "scroll-margin-top": [],
  "scroll-padding": ["auto"],
  "scroll-padding-block": ["auto"],
  "scroll-padding-block-end": ["auto"],
  "scroll-padding-block-start": ["auto"],
  "scroll-padding-bottom": ["auto"],
  "scroll-padding-inline": ["auto"],
  "scroll-padding-inline-end": ["auto"],
  "scroll-padding-inline-start": ["auto"],
  "scroll-padding-left": ["auto"],
  "scroll-padding-right": ["auto"],
  "scroll-padding-top": ["auto"],
  "scroll-snap-align": ["none", "start", "end", "center"],
  "scroll-snap-coordinate": ["none", "position"],
  "scroll-snap-destination": ["position"],
  "scroll-snap-points-x": ["none", "repeat"],
  "scroll-snap-points-y": ["none", "repeat"],
  "scroll-snap-stop": ["normal", "always"],
  "scroll-snap-type": [
    "none",
    "x",
    "y",
    "block",
    "inline",
    "both",
    "mandatory",
    "proximity",
  ],
  "scroll-snap-type-x": ["none", "mandatory", "proximity"],
  "scroll-snap-type-y": ["none", "mandatory", "proximity"],
  "scroll-timeline": [],
  "scroll-timeline-axis": ["block", "inline"],
  "scroll-timeline-name": ["none", "dashed-ident"],
  "scrollbar-color": ["auto"],
  "scrollbar-gutter": ["auto", "stable", "both-edges"],
  "scrollbar-width": ["auto", "thin", "none"],
  "shape-image-threshold": ["opacity-value"],
  "shape-margin": [],
  "shape-outside": ["none", "shape-box", "basic-shape"],
  "shape-rendering": [
    "auto",
    "optimize",
    "peed",
    "crisp",
    "dges",
    "geometric",
    "recision",
  ],
  "stop-color": [],
  "stop-opacity": [],
  stroke: ["paint"],
  "stroke-dasharray": ["none", "dasharray"],
  "stroke-dashoffset": [],
  "stroke-linecap": ["butt", "round", "square"],
  "stroke-linejoin": [
    "miter",
    "miter-clip",
    "round",
    "bevel",
    "arcs",
  ],
  "stroke-miterlimit": [],
  "stroke-opacity": [],
  "stroke-width": [],
  "tab-size": ["integer"],
  "table-layout": ["auto", "fixed"],
  "text-align": [
    "start",
    "end",
    "left",
    "right",
    "center",
    "justify",
    "match-parent",
  ],
  "text-align-last": [
    "auto",
    "start",
    "end",
    "left",
    "right",
    "center",
    "justify",
  ],
  "text-anchor": ["start", "middle", "end"],
  "text-box": ["normal"],
  "text-box-edge": ["auto", "text-edge"],
  "text-box-trim": [
    "none",
    "trim-start",
    "trim-end",
    "trim-both",
  ],
  "text-combine-upright": [
    "none",
    "all",
    "digits",
    "integer",
  ],
  "text-decoration": [],
  "text-decoration-color": [],
  "text-decoration-line": [
    "none",
    "underline",
    "overline",
    "line-through",
    "blink",
    "spelling-error",
    "grammar-error",
  ],
  "text-decoration-skip": [
    "none",
    "objects",
    "spaces",
    "leading-spaces",
    "trailing-spaces",
    "edges",
    "box-decoration",
  ],
  "text-decoration-skip-ink": ["auto", "all", "none"],
  "text-decoration-style": [
    "solid",
    "double",
    "dotted",
    "dashed",
    "wavy",
  ],
  "text-decoration-thickness": ["auto", "from-font"],
  "text-emphasis": [],
  "text-emphasis-color": [],
  "text-emphasis-position": [
    "auto",
    "over",
    "under",
    "right",
    "left",
  ],
  "text-emphasis-style": [
    "none",
    "filled",
    "open",
    "dot",
    "circle",
    "double-circle",
    "triangle",
    "sesame",
    "string",
  ],
  "text-indent": ["hanging", "each-line"],
  "text-justify": [
    "auto",
    "inter-character",
    "inter-word",
    "none",
  ],
  "text-orientation": ["mixed", "upright", "sideways"],
  "text-overflow": ["clip", "ellipsis", "string"],
  "text-rendering": [
    "auto",
    "optimize",
    "peed",
    "optimize",
    "egibility",
    "geometric",
    "recision",
  ],
  "text-shadow": ["none", "shadow-t"],
  "text-size-adjust": ["none", "auto"],
  "text-spacing-trim": [
    "space-all",
    "normal",
    "space-first",
    "trim-start",
    "trim-both",
    "trim-all",
    "auto",
  ],
  "text-transform": [
    "none",
    "capitalize",
    "uppercase",
    "lowercase",
    "full-width",
    "full-size-kana",
  ],
  "text-underline-offset": ["auto"],
  "text-underline-position": [
    "auto",
    "from-font",
    "under",
    "left",
    "right",
  ],
  "text-wrap": [],
  "text-wrap-mode": ["wrap", "nowrap"],
  "text-wrap-style": [
    "auto",
    "balance",
    "stable",
    "pretty",
  ],
  "timeline-scope": ["none", "dashed-ident"],
  top: ["auto"],
  "touch-action": [
    "auto",
    "none",
    "pan-x",
    "pan-left",
    "pan-right",
    "pan-y",
    "pan-up",
    "pan-down",
    "pinch-zoom",
    "manipulation",
  ],
  transform: ["none", "transform-list"],
  "transform-box": [
    "content-box",
    "border-box",
    "fill-box",
    "stroke-box",
    "view-box",
  ],
  "transform-origin": [
    "left",
    "center",
    "right",
    "top",
    "bottom",
    "left",
    "center",
    "right",
    "top",
    "center",
    "bottom",
  ],
  "transform-style": ["flat", "preserve-", "d"],
  transition: ["single-transition"],
  "transition-behavior": ["transition-behavior-value"],
  "transition-delay": [],
  "transition-duration": [],
  "transition-property": [
    "none",
    "single-transition-property",
  ],
  "transition-timing-function": ["easing-function"],
  translate: ["none"],
  "unicode-bidi": [
    "normal",
    "embed",
    "isolate",
    "bidi-override",
    "isolate-override",
    "plaintext",
  ],
  "user-select": ["auto", "text", "none", "contain", "all"],
  "vector-effect": [
    "none",
    "non-scaling-stroke",
    "non-scaling-size",
    "non-rotation",
    "fixed-position",
  ],
  "vertical-align": [
    "baseline",
    "sub",
    "super",
    "text-top",
    "text-bottom",
    "middle",
    "top",
    "bottom",
  ],
  "view-timeline": [],
  "view-timeline-axis": ["block", "inline"],
  "view-timeline-inset": ["auto"],
  "view-timeline-name": ["none", "dashed-ident"],
  "view-transition-name": ["none", "custom-ident"],
  visibility: ["visible", "hidden", "collapse"],
  "white-space": [
    "normal",
    "pre",
    "nowrap",
    "pre-wrap",
    "pre-line",
    "break-spaces",
  ],
  "white-space-collapse": [
    "collapse",
    "discard",
    "preserve",
    "preserve-breaks",
    "preserve-spaces",
    "break-spaces",
  ],
  widows: ["integer"],
  width: [
    "auto",
    "min-content",
    "max-content",
    "fit-content",
    "fit-content",
    "calc-size",
    "anchor-size",
  ],
  "will-change": ["auto", "animateable-feature"],
  "word-break": [
    "normal",
    "break-all",
    "keep-all",
    "break-word",
    "auto-phrase",
  ],
  "word-spacing": ["normal"],
  "word-wrap": ["normal", "break-word"],
  "writing-mode": [
    "horizontal-tb",
    "vertical-rl",
    "vertical-lr",
    "sideways-rl",
    "sideways-lr",
  ],
  x: [],
  y: [],
  "z-index": ["auto", "integer"],
  zoom: ["normal", "reset"],
};
export const styleSuggestionMapKeys = Object.keys(
  styleSuggestionMap
);
